### ISSUE TITLE
Page 76 is missing from [Hi-Res Graphics TMS9918 BYTE 0882.pdf]

### ISSUE THREAD

**Issue by bissonex** [cbmeeks/TMS9918#2]
The seminal article "High-Resolution Sprite-Oriented Color Graphics" is missing page 76.
see #1 for the updated document

**Comment by cbmeeks** [comment]
Thanks for the pull request! 

I never noticed that page was missing.

Thanks again.

**Comment by bissonex** [comment]
Now I would be grateful if someone knows how to replace the source copy at https://archive.org/details/Hi-Res_Graphics_TMS9918_BYTE_0882.

**Comment by cbmeeks** [comment]
Yeah, not sure on that one.  Maybe you can contact the uploader (his name is on the archive page).  Or, maybe upload your version and put a review on mentioning your correction.

If you like, I can look into this.

**Comment by factus10** [comment]
<div></div><div>Yeah, not sure on that one.  Maybe you can contact the uploader (his name is on the archive page).  Or, maybe upload your version and put a review on mentioning your correction.
<br/>
<br/>If you like, I can look into this.
<br/>
<br/>-- 
<br/>You are receiving this because you are subscribed to this thread.
<br/>Reply to this email directly or view it on GitHub:
<br/>https://github.com/cbmeeks/TMS9918/issues/2#issuecomment-754747921</div>
